USE [master]
GO

/****** Object:  Database [Productos_Defectuosos]    Script Date: 29/8/2024 20:17:24 ******/
CREATE DATABASE [Productos_Defectuosos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Productos_Defectuosos', FILENAME = N'C:\Users\Santino\Desktop\Lourdes\Archivos y apps\SQL archivos\MSSQL16.SQLEXPRESS02\MSSQL\DATA\Productos_Defectuosos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Productos_Defectuosos_log', FILENAME = N'C:\Users\Santino\Desktop\Lourdes\Archivos y apps\SQL archivos\MSSQL16.SQLEXPRESS02\MSSQL\DATA\Productos_Defectuosos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Productos_Defectuosos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Productos_Defectuosos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET ARITHABORT OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Productos_Defectuosos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Productos_Defectuosos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Productos_Defectuosos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Productos_Defectuosos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Productos_Defectuosos] SET  MULTI_USER 
GO

ALTER DATABASE [Productos_Defectuosos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Productos_Defectuosos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Productos_Defectuosos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Productos_Defectuosos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Productos_Defectuosos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Productos_Defectuosos] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Productos_Defectuosos] SET QUERY_STORE = ON
GO

ALTER DATABASE [Productos_Defectuosos] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Productos_Defectuosos] SET  READ_WRITE 
GO

